apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8099
    jsonData:
      version: Flux
      organization: nef
      defaultBucket: location_events
      tlsSkipVerify: true
    secureJsonData:
      token: nef-super-secret-token
    isDefault: true
    editable: true
