services:
  # MongoDB service
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nef-network

  test-server:
    image: python:3.12.10-slim
    container_name: test_server
    ports:
      - "8001:8001"
    volumes:
      - ./MonitoringEventAPI/test_server.py:/test_server.py
    restart: unless-stopped
    command: ["/bin/sh", "-c", "python test_server.py"]
    networks:
      - nef-network

  # The NEF service depends on the db and backend services.(Panagiwths kai Andreas)
  nef:
    build:
      context: ./MonitoringEventAPI
      args:
        AUTH_ENABLED: ${AUTH_ENABLED}
    image: ghcr.io/front-research-group/nef-monitoring:latest
    container_name: nef
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:9999" # 9999 for .72
    depends_on:
      mongodb:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nef-network

  core_crowler:
      build:
        context: ./core_crowler
      image: ghcr.io/front-research-group/core-crowler:latest
      container_name: core_crowler
      restart: unless-stopped
      env_file: .env
      depends_on:
        mongodb:
          condition: service_healthy
      networks:
        - nef-network
      user: root
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:

networks:
  nef-network:
    driver: bridge
